# Generated by Django 3.0.5 on 2022-05-18 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('BM25', 'Okapi BM25'), ('DFR', 'Divergence from Randomness (DFR)'), ('DFI', 'Divergence from Independence (DFI)'), ('IB', 'Information based model'), ('LMDirichlet', 'Language Model: Dirichlet priors'), ('LMJelinekMercer', 'Language Model: Jelinek-Mercer smoothing method')], default='BM25', max_length=50)),
                ('num_repl', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('max_result_window', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)])),
                ('k1', models.CharField(default='1.2', max_length=10)),
                ('b', models.CharField(default='0.75', max_length=10)),
                ('discount_overlaps', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='True', max_length=10)),
                ('basic_model', models.CharField(choices=[('g', 'Geometric approximation of Bose-Einstein'), ('if', 'Inverse Term Frequency'), ('in', 'Inverse Document Frequency'), ('ine', 'Inverse Expected Document Frequency')], default='g', max_length=10)),
                ('after_effect', models.CharField(choices=[('b', 'Bernoulli processes'), ('l', "Laplace's law of succession")], default='b', max_length=10)),
                ('normalization_dfr', models.CharField(choices=[('no', 'no'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('z', 'z')], default='h1', max_length=10)),
                ('normalization_parameter_dfr', models.CharField(default='1.0', max_length=10)),
                ('independence_measure', models.CharField(choices=[('standardized', 'Standardized'), ('saturated', 'Saturated'), ('chisquared', 'Normalized chi-squared')], default='standardized', max_length=15)),
                ('distribution', models.CharField(choices=[('ll', 'Log-logistic'), ('spl', 'Smoothed power-law')], default='ll', max_length=10)),
                ('lambda_ib', models.CharField(choices=[('df', 'Document frequency'), ('ttf', 'Total term frequency')], default='df', max_length=10)),
                ('normalization_ib', models.CharField(choices=[('no', 'no'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('z', 'z')], default='h1', max_length=10)),
                ('normalization_parameter_ib', models.CharField(default='1.0', max_length=10)),
                ('mu', models.CharField(default='2000', max_length=10)),
                ('lambda_jelinek', models.CharField(default='.1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchableIndicesConfigs',
            fields=[
                ('index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('index_model', models.CharField(choices=[('Diario', 'Diario'), ('DiarioSegmentado', 'DiarioSegmentado'), ('Processo', 'Processo'), ('Licitacao', 'Licitacao')], max_length=50)),
                ('searchable', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('regular', 'regular'), ('replica', 'replica')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_per_page', models.IntegerField(default=10)),
                ('use_entities_in_search', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightedSearchFieldsConfigs',
            fields=[
                ('field', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=1)),
                ('searchable', models.BooleanField(default=True)),
            ],
        ),
    ]
