# Generated by Django 3.0.5 on 2021-12-08 17:39

from django.db import migrations
from mpmg.services.elastic import Elastic

def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('id_usuario', 'text')
    m.field('texto', 'text')
    m.field('tipo', 'text')
    m.field('data_criacao', 'date')
    m.field('data_visualizacao', 'date')
    m.save('notifications')

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20210805_1816'),
    ]

    operations = [
        migrations.RunPython(create_index)
    ]
