# Generated by Django 3.0.5 on 2021-11-17 17:43

from django.db import migrations
from mpmg.services.elastic import Elastic

def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('ui_name', 'text')
    m.field('es_index_name', 'text')
    m.field('class_name', 'text')
    m.field('group', 'text')
    m.field('active', 'boolean')
    m.save('config_indices')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20210805_1816'),
    ]

    operations = [
        migrations.RunPython(create_index)
    ]
