# Generated by Django 3.0.5 on 2021-11-17 19:42

from django.db import migrations
from mpmg.services.elastic import Elastic

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_indices', id=1, body={'ui_name':'Diários', 'es_index_name':'diarios', 'class_name':'Diario', 'group':'regular', 'active': True})
    elastic.es.index(index='config_indices', id=2, body={'ui_name':'Diários Segmentados', 'es_index_name':'diarios_segmentado', 'class_name':'DiarioSegmentado', 'group':'regular', 'active': True})
    elastic.es.index(index='config_indices', id=3, body={'ui_name':'Licitações', 'es_index_name':'licitacoes', 'class_name':'Licitacao', 'group':'regular', 'active': True})
    elastic.es.index(index='config_indices', id=4, body={'ui_name':'Processos', 'es_index_name':'processos', 'class_name':'Processo', 'group':'regular', 'active': True})

    elastic.es.index(index='config_indices', id=5, body={'ui_name':'Diários Réplica', 'es_index_name':'diarios-replica', 'class_name':'Diario', 'group':'replica', 'active': True})
    elastic.es.index(index='config_indices', id=6, body={'ui_name':'Diários Segmentados Réplica', 'es_index_name':'diarios_segmentado-replica', 'class_name':'DiarioSegmentado', 'group':'replica', 'active': True})
    elastic.es.index(index='config_indices', id=7, body={'ui_name':'Licitações Réplica', 'es_index_name':'licitacoes-replica', 'class_name':'Licitacao', 'group':'replica', 'active': True})
    elastic.es.index(index='config_indices', id=8, body={'ui_name':'Processos Réplica', 'es_index_name':'processos-replica', 'class_name':'Processo', 'group':'replica', 'active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_create_configindices_index'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
