# Generated by Django 3.0.5 on 2021-12-08 17:55

from django.db import migrations
from mpmg.services.elastic import Elastic


def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('user_id', 'text')
    m.field('notification_id', 'text')
    m.field('recommended_doc_index', 'text')
    m.field('recommended_doc_id', 'text')
    m.field('matched_from', 'text')
    m.field('original_query_text', 'text')
    m.field('original_doc_index', 'text')
    m.field('original_doc_id', 'text')
    m.field('date', 'date')
    m.field('accepted', 'boolean')
    m.save('doc_recommendations')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_create_notifications_index'),
    ]

    operations = [
        migrations.RunPython(create_index)
    ]
