# Generated by Django 3.0.5 on 2021-12-08 17:55

from django.db import migrations
from mpmg.services.elastic import Elastic
from elasticsearch_dsl import Keyword

def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('id_usuario', 'text')
    m.field('id_notificacao',  'text', fields={'keyword': Keyword()})
    m.field('indice_doc_recomendado', 'text')
    m.field('id_doc_recomendado', 'text')
    m.field('titulo_doc_recomendado', 'text')
    m.field('evidencia', 'text')
    m.field('evidencia_texto_consulta', 'text')
    m.field('evidencia_indice_doc', 'text')
    m.field('evidencia_id_doc', 'text')
    m.field('evidencia_titulo_doc', 'text')
    m.field('data_criacao', 'date')
    m.field('data_visualizacao', 'date')
    m.field('similaridade', 'float')
    m.field('aprovado', 'boolean')
    m.save('doc_recommendations')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_create_notifications_index'),
    ]

    operations = [
        migrations.RunPython(create_index)
    ]
