# Generated by Django 3.0.5 on 2022-01-13 18:03

from django.db import migrations
from mpmg.services.elastic import Elastic


def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('ui_name', 'text')
    m.field('es_index_name', 'text')
    m.field('amount', 'integer')
    m.field('active', 'boolean')
    m.save('config_recommendation_sources')

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_recommendation_sources', id=1, body={'ui_name': 'Diários', 'es_index_name': 'diarios_segmentado', 'amount':1000, 'active': True})
    elastic.es.index(index='config_recommendation_sources', id=2, body={'ui_name': 'Processos', 'es_index_name': 'processos', 'amount':1000, 'active': True})
    elastic.es.index(index='config_recommendation_sources', id=3, body={'ui_name': 'Licitações', 'es_index_name': 'licitacoes', 'amount':1000, 'active': True})
    

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_create_recommendations_index'),
    ]

    operations = [
        migrations.RunPython(create_index),
        migrations.RunPython(insert_data)
    ]
