# Generated by Django 3.0.5 on 2022-01-13 18:03

from django.db import migrations
from mpmg.services.elastic import Elastic
from elasticsearch_dsl import Keyword


def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('nome', 'text')
    m.field('nome_indice', 'text', fields={'keyword': Keyword()})
    m.field('quantidade', 'integer')
    m.field('ativo', 'boolean')
    m.save('config_recommendation_sources')

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_recommendation_sources', id='diarios_segmentado', body={'nome': 'Diários', 'nome_indice': 'diarios_segmentado', 'quantidade':1000, 'ativo': True})
    elastic.es.index(index='config_recommendation_sources', id='processos', body={'nome': 'Processos', 'nome_indice': 'processos', 'quantidade':1000, 'ativo': True})
    elastic.es.index(index='config_recommendation_sources', id='licitacoes', body={'nome': 'Licitações', 'nome_indice': 'licitacoes', 'quantidade':1000, 'ativo': True})
    

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_create_recommendations_index'),
    ]

    operations = [
        migrations.RunPython(create_index),
        migrations.RunPython(insert_data)
    ]
