# Generated by Django 3.0.5 on 2022-01-13 18:05

from django.db import migrations
from mpmg.services.elastic import Elastic
from elasticsearch_dsl import Keyword


def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('nome', 'text')
    m.field('tipo_evidencia', 'text', fields={'keyword': Keyword()})
    m.field('nome_indice', 'text')
    m.field('quantidade', 'integer')
    m.field('similaridade_minima', 'integer')
    m.field('top_n_recomendacoes', 'integer')
    m.field('ativo', 'boolean')
    m.save('config_recommendation_evidences')

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_recommendation_evidences', id='bookmark', body={
                     'nome': 'Favoritos', 'tipo_evidencia': 'bookmark', 'nome_indice': 'bookmark', 'quantidade': 5, 'similaridade_minima': 60, 'top_n_recomendacoes': 5, 'ativo': True})
    elastic.es.index(index='config_recommendation_evidences', id='query', body={
                     'nome': 'Consultas', 'tipo_evidencia': 'query', 'nome_indice': 'log_buscas', 'quantidade': 5, 'similaridade_minima': 60, 'top_n_recomendacoes': 5, 'ativo': True})
    elastic.es.index(index='config_recommendation_evidences', id='click', body={
                     'nome': 'Cliques', 'tipo_evidencia': 'click', 'nome_indice': 'log_clicks', 'quantidade': 5, 'similaridade_minima': 60, 'top_n_recomendacoes': 5, 'ativo': True})
class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_create_config_recommendation_sources_index'),
    ]

    operations = [
        migrations.RunPython(create_index),
        migrations.RunPython(insert_data)
    ]
