# Generated by Django 3.0.5 on 2022-01-13 18:05

from django.db import migrations
from mpmg.services.elastic import Elastic
from elasticsearch_dsl import Keyword


def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('ui_name', 'text')
    m.field('evidence_type', 'text', fields={'keyword': Keyword()})
    m.field('es_index_name', 'text')
    m.field('amount', 'integer')
    m.field('min_similarity', 'integer')
    m.field('top_n_recommendations', 'integer')
    m.field('active', 'boolean')
    m.save('config_recommendation_evidences')

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_recommendation_evidences', id=1, body={'ui_name': 'Favoritos', 'evidence_type': 'bookmark', 'es_index_name': 'bookmark', 'amount':5, 'min_similarity': 60, 'top_n_recommendations': 5, 'active': True})
    elastic.es.index(index='config_recommendation_evidences', id=2, body={'ui_name': 'Consultas', 'evidence_type': 'query', 'es_index_name': 'log_buscas', 'amount':5, 'min_similarity': 60, 'top_n_recommendations': 5, 'active': True})
    elastic.es.index(index='config_recommendation_evidences', id=3, body={'ui_name': 'Cliques', 'evidence_type': 'click', 'es_index_name': 'log_clicks', 'amount':5, 'min_similarity': 60, 'top_n_recommendations': 5, 'active': True})

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_create_config_recommendation_sources_index'),
    ]

    operations = [
        migrations.RunPython(create_index),
        migrations.RunPython(insert_data)
    ]
