# Generated by Django 3.0.5 on 2021-11-18 13:53

from django.db import migrations
from mpmg.services.elastic import Elastic

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_fields', id=1, body={'ui_name':'Fonte',          'field_name': 'fonte',                'weight': 1, 'searchable': False, 'retrievable': True})
    elastic.es.index(index='config_fields', id=2, body={'ui_name':'Título',         'field_name': 'titulo',               'weight': 1, 'searchable': False, 'retrievable': True})
    elastic.es.index(index='config_fields', id=3, body={'ui_name':'Conteúdo',       'field_name': 'conteudo',             'weight': 1, 'searchable': True,  'retrievable': True})
    elastic.es.index(index='config_fields', id=4, body={'ui_name':'Pessoas',        'field_name': 'entidade_pessoa',      'weight': 1, 'searchable': True,  'retrievable': True})
    elastic.es.index(index='config_fields', id=5, body={'ui_name':'Organizações',   'field_name': 'entidade_organizacao', 'weight': 1, 'searchable': False, 'retrievable': True})
    elastic.es.index(index='config_fields', id=6, body={'ui_name':'Municípios',     'field_name': 'entidade_municipio',   'weight': 1, 'searchable': False, 'retrievable': True})
    elastic.es.index(index='config_fields', id=7, body={'ui_name':'Locais',         'field_name': 'entidade_local',       'weight': 1, 'searchable': False, 'retrievable': True})
    elastic.es.index(index='config_fields', id=8, body={'ui_name':'Vetores Densos', 'field_name': 'embedding_vector',     'weight': 1, 'searchable': False, 'retrievable': True})


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_create_configfields_index'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
