# Generated by Django 3.0.5 on 2021-11-18 19:12

from django.db import migrations
from mpmg.services.elastic import Elastic

def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('results_per_page', 'integer')
    m.field('highlight_field', 'text')
    m.field('identify_entities_in_query', 'boolean')
    m.field('use_semantic_vectors_in_search', 'boolean')
    m.save('config_options')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_insert_configfields_data'),
    ]

    operations = [
        migrations.RunPython(create_index)
    ]
