# Generated by Django 3.0.5 on 2021-11-18 19:22

from django.db import migrations
from mpmg.services.elastic import Elastic

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_options', id=1, body={'results_per_page':10, 'highlight_field':'conteudo', 'identify_entities_in_query':False, 'use_semantic_vectors_in_search':True})

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_create_configoptions_index'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
