# Generated by Django 3.0.5 on 2021-11-19 14:25

from django.db import migrations
from mpmg.services.elastic import Elastic

def create_index(apps, schema_editor):
    elastic = Elastic()
    m = elastic.dsl.Mapping()
    m.field('entity_type', 'text')
    m.field('field_name', 'text')
    m.save('config_entities_mapping')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_insert_configoptions_data'),
    ]

    operations = [
        migrations.RunPython(create_index)
    ]
