# Generated by Django 3.0.5 on 2021-11-19 14:28

from django.db import migrations
from mpmg.services.elastic import Elastic

def insert_data(apps, schema_editor):
    elastic = Elastic()
    elastic.es.index(index='config_entities_mapping', id=1,  body={'entity_type': 'PESSOA',               'field_name': 'entidade_pessoa'})
    elastic.es.index(index='config_entities_mapping', id=2,  body={'entity_type': 'ORGANIZACAO',          'field_name': 'entidade_organizacao'})
    elastic.es.index(index='config_entities_mapping', id=3,  body={'entity_type': 'LOCAL',                'field_name': 'entidade_local',})
    elastic.es.index(index='config_entities_mapping', id=4,  body={'entity_type': 'TEMPO',                'field_name': 'entidade_tempo',})
    elastic.es.index(index='config_entities_mapping', id=5,  body={'entity_type': 'LEGISLACAO',           'field_name': 'entidade_legislacao'})
    elastic.es.index(index='config_entities_mapping', id=6,  body={'entity_type': 'JURISPRUDENCIA',       'field_name': 'entidade_jurisprudencia'})
    elastic.es.index(index='config_entities_mapping', id=7,  body={'entity_type': 'CPF',                  'field_name': 'entidade_cpf',})
    elastic.es.index(index='config_entities_mapping', id=8,  body={'entity_type': 'CNPJ',                 'field_name': 'entidade_cnpj'})
    elastic.es.index(index='config_entities_mapping', id=9,  body={'entity_type': 'CEP',                  'field_name': 'entidade_cep'})
    elastic.es.index(index='config_entities_mapping', id=10, body={'entity_type': 'MUNICIPIO',            'field_name': 'entidade_municipio'})
    elastic.es.index(index='config_entities_mapping', id=11, body={'entity_type': 'NUM_LICIT_OU_MODALID', 'field_name': 'entidade_processo_licitacao'})


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_create_configentity_index'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
