version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/NER/M02"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    
  - package-ecosystem: "npm"
    directory: "/NER/M02/doccano"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
      
