version: '3.7'

services:
    # client:
    #     build:
    #         context: .
    #         dockerfile: ./misc/docker/client/Dockerfile
    #     command: ./django_run.sh
    #     ports:
    #         - "8086:8086"
    #     expose:
    #         - 8086
    #     env_file:
    #         - ./misc/docker/client/.env
    #     restart: on-failure
    api:
        build:
            context: .
            dockerfile: ./misc/docker/api/Dockerfile
        command: ./django_run.sh
        volumes:
            - static_volume:/home/django/mpmg/staticfiles
            - migrations:/home/django/mpmg/api/mpmgmain/migrations
        env_file:
            - ./misc/docker/api/.env
        restart: on-failure
        network_mode: host
volumes:
    static_volume:
    migrations:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './api/mpmg/services/migrations'
