version: '3.7'

services:
    client:
        build:
            context: .
            dockerfile: ./docker/client/Dockerfile
        command: ./django_run.sh
        ports:
            - "8086:8086"
        expose:
            - 8086
        env_file:
            - ./docker/config/.env
        restart: on-failure
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        command: ./django_run.sh
        ports:
            - "8087:8087"
        expose:
            - 8087
        env_file:
            - ./docker/config/.env
        restart: on-failure
